# 交易策略
[strategy]
max_positions = 4 # 持仓数量的上限

[data]
test_data_length = 45
val_data_length = 45
initial_buffer_data = 120
train_scaler_dir = "config/assets/scalers/"

[models]
model_path = "models/saved_models"
visualization_path = "/models/visualization"

[stop_loss]
max_profit_path = "config/assets/stop_loss/max_profit.pkl"
